//
// README: Portions of this file are merged at file generation
// time. Edits can be made *only* in between specified code blocks, look
// for keywords <Begin user code> and <End user code>.
//
//////////////////////////////////////////////////////////////
//
// Header file for CUIreflnviewprops
//
//    Created by Builder Xcessory Version 5.0.
//    Generated by Code Generator Xcessory 5.0 (05/22/98) .
//
//    This class is a user interface "component", as described
//    in "Object-Oriented Programming with C++ and OSF/Motif",
//    by Douglas Young, Prentice Hall, 1992. ISBN 0-13-630252-1
//
//////////////////////////////////////////////////////////////


// Begin user code block <file_comments>
//
// Copyright (c) 1997 Molecular Structure Corporation
//
// RESTRICTED RIGHTS NOTICE SHORT FORM (JUNE 1987)
//
// Use, reproduction, or disclosure is subject to restrictions set
// forth in Contract No. W-31-109-ENG-38 and Contract No. 
// 943072401 with the University of Chicago, Operator of
// Argonne National Laboratory.
//
// CUIreflnviewprops.h    Initial author: YY Xiao           ?-May-1997
//    This file is the header file for user interface class CUIreflnviewprops.
/*
 *
 * Copyright (C) 2014 Rigaku Americas Corporation
 *                    9009 New Trails Drive
 *                    The Woodlands, TX, USA  77381
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *    * Redistributions of source code must retain the above copyright
 *      notice(s), this list of conditions and the following disclaimer.
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice(s), this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *    * Neither the name of the Rigaku Americas Corporation nor the 
 *      names of its contributors may be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL RIGAKU AMERICAS CORPORATION BE LIABLE 
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS INTERUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 *
*/ 

// End user code block <file_comments>

#ifndef CUIreflnviewprops_H
#define CUIreflnviewprops_H
#include "UIComponent.h"
class CUIom9;

//
// Globally included information (change thru Output File Names Dialog).
//


//
// Class Specific Includes (change thru the class in Resource Editor).
//



// Begin user code block <head>

#include <string.h>
#include "CXhelp.h"

typedef struct _tagReflnProps 
{
  Cstring sReflnColor;
  int nReflnPredObs;
  int nReflnSymbol;
//  int nReflnRestrictRange;
//  int nReflnRestrictValues;
  float a6fReflnSize[6];
} tagReflnProps;


// End user code block <head>

class CUIreflnviewprops : public UIComponent

// Begin user code block <superclass>
// End user code block <superclass>
{

// Begin user code block <friends>
// End user code block <friends>

  public:

    CUIreflnviewprops(const char *, Widget);
    CUIreflnviewprops(const char *);
    virtual ~CUIreflnviewprops();
    virtual void create(Widget);
    const char *const  className();
    
    // Begin user code block <public>

    XtPointer  m_pObj;
    void (*m_prvOKCallback) (XtPointer, const tagReflnProps*);
    void vSetValues(const tagReflnProps&, const Cstring, const int);
    void vGetValues(tagReflnProps*);

    // End user code block <public>
  protected:
    // Classes created by this class
    CUIom9* _cUIom9RestrictRange;
    CUIom9* _cUIom9PredObs;
    CUIom9* _cUIom9Symbol;
    CUIom9* _cUIom9Color;
    CUIom9* _cUIom9Filename;
    
    // Widgets created by this class
    Widget _CUIreflnviewprops;
    Widget _fmRefln;
    Widget _lbRotRange;
    Widget _lbRestrictRange;
    Widget _lbPredObs;
    Widget _lbColor;
    Widget _tfRotRange;
    Widget _lbSymbol;
    Widget _tfSize;
    Widget _lbSize;
    Widget _lbReflnName;
    
    // These virtual functions are called from the private callbacks 
    // or event handlers intended to be overridden in derived classes
    // to define actions
    
    virtual void vHTMLHelp(Widget, XtPointer, XtPointer);
    virtual void vReflnViewPropSelectCB(Widget, XtPointer, XtPointer);
    
    // Begin user code block <protected>

    tagReflnProps m_tReflnProps;
    Cstring m_sReflnFilename;
    int m_nReflnNum;

    void vUpdateWidgets(void);
    void vReadWidgets(void);

    // End user code block <protected>
  private: 
    
    //
    // Default application and class resources.
    //
    static String         _defaultCUIreflnviewpropsResources[];
    static UIAppDefault   _appDefaults[];
    static Boolean        _initAppDefaults;
    //
    // Callback client data.
    //
    UICallbackStruct  *_clientDataStructs;
    
    //
    // Callbacks to interface with Motif.
    //
    static void vHTMLHelpCallback(Widget, XtPointer, XtPointer);
    static void vReflnViewPropSelectCBCallback(Widget, XtPointer, XtPointer);
    
    // Begin user code block <private>

    CXhelp *m_poXhelp;

    void vSetLabel(Widget, char *);
  
    static  void vCUIom9CBCallback(XtPointer, Widget, XtPointer, XtPointer);
    virtual void vCUIom9CB(XtPointer, Widget, XtPointer, XtPointer);
    // End user code block <private>
};

// Begin user code block <tail>
// End user code block <tail>
#endif
