//
// Copyright (c) 1997 Molecular Structure Corporation
//
// RESTRICTED RIGHTS NOTICE SHORT FORM (JUNE 1987)
//
// Use, reproduction, or disclosure is subject to restrictions set
// forth in Contract No. W-31-109-ENG-38 and Contract No. 
// 943072401 with the University of Chicago, Operator of
// Argonne National Laboratory.
//
// CUItextnumentry.h       Initial author: J.W. Pflugrath           9-Apr-1997
//    Class definition for a user interface widget to adjust textfield numbers
//    with arrow buttons and virtual keypad.
/*
 *
 * Copyright (C) 2014 Rigaku Americas Corporation
 *                    9009 New Trails Drive
 *                    The Woodlands, TX, USA  77381
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *    * Redistributions of source code must retain the above copyright
 *      notice(s), this list of conditions and the following disclaimer.
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice(s), this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *    * Neither the name of the Rigaku Americas Corporation nor the 
 *      names of its contributors may be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL RIGAKU AMERICAS CORPORATION BE LIABLE 
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS INTERUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 *
*/

//
// README: Portions of this file are merged at file generation
// time. Edits can be made *only* in between specified code blocks, look
// for keywords <Begin user code> and <End user code>.
//
//////////////////////////////////////////////////////////////
//
// Header file for CUItextnumentry
//
//    This file is generated by Builder Xcessory 3.5.1.
//
//    This class is a user interface "component", as described
//    in "Object-Oriented Programming with C++ and OSF/Motif",
//    by Douglas Young, Prentice Hall, 1992. ISBN 0-13-630252-1
//
//////////////////////////////////////////////////////////////
#ifndef CUItextnumentry_H
#define CUItextnumentry_H
#include "UIComponent.h"

//
// Globally included information (change thru Output File Names Dialog).
//


//
// Class Specific Includes (change thru the class in Resource Editor).
//



// Begin user code block <head> 
#include "Cstring.h"
// End user code block <head> 

class CUItextnumentry : public UIComponent
{

  public:

    CUItextnumentry(const char *, Widget);
    CUItextnumentry(const char *);
    virtual ~CUItextnumentry();
    virtual void create(Widget);
    const char *const  className();
    
    // Begin user code block <public> 
      void vSetTextField(Widget w);
    // End user code block <public> 
  protected:
    // Classes created by this class
    
    // Widgets created by this class
    Widget _CUItextnumentry;
    Widget _lbDecimal;
    Widget _abUp10;
    Widget _abUp9;
    Widget _abUp8;
    Widget _abUp7;
    Widget _abUp6;
    Widget _abUp5;
    Widget _abDown10;
    Widget _abDown9;
    Widget _abDown8;
    Widget _abDown7;
    Widget _abDown6;
    Widget _abDown5;
    Widget _pbRecall;
    Widget _pbDelete;
    Widget _abUp4;
    Widget _abDown4;
    Widget _abDown3;
    Widget _abUp3;
    Widget _pbCancel;
    Widget _pbClear;
    Widget _abDown2;
    Widget _abUp2;
    Widget _abDown1;
    Widget _abUp1;
    Widget _pbEnter;
    Widget _pbPlusMinus;
    Widget _pbDot;
    Widget _pb9;
    Widget _pb8;
    Widget _pb7;
    Widget _pb6;
    Widget _pb5;
    Widget _pb4;
    Widget _pb3;
    Widget _pb2;
    Widget _pb1;
    Widget _pb0;
    
    // These virtual functions are called from the private callbacks 
    // or event handlers intended to be overridden in derived classes
    // to define actions
    
    virtual void vButtonCB(Widget, XtPointer, XtPointer);
    
    // Begin user code block <protected> 
    // End user code block <protected> 
  private: 
    
    //
    // Default application and class resources.
    //
    static String         _defaultCUItextnumentryResources[];
    static UIAppDefault   _appDefaults[];
    static Boolean        _initAppDefaults;
    //
    // Callback client data.
    //
    UICallbackStruct  *_clientDataStructs;
    
    //
    // Callbacks to interface with Motif.
    //
    static void vButtonCBCallback(Widget, XtPointer, XtPointer);
    
    // Begin user code block <private> 
      Widget   m_wTextField;
      Widget  *m_apwArrowButtons[20];
      double   m_dNumber;
      double   m_dNumberOrig;
      double   m_dIncrement[10];
      Cstring  m_sTextOrig;
      Cstring  m_sTextCurr;
      Cstring  m_sFormat;

    // End user code block <private> 
};

// Begin user code block <tail> 
// End user code block <tail> 
#endif
